[workspace]
resolver = "2"
members = ["rawr-rust", "test-codegen/harness"]

[workspace.dependencies]
linkme = "0.3.31"
rawr = { path = "rawr-rust" }
serde = "1.0.217"
walkdir = "2.5.0"
colored = "2.2.0"
