[package]
name = "rawr"
version = "0.1.0"
edition = "2021"

[dependencies]
rawr_macros = { path = "macros" }
dashmap.workspace = true
futures.workspace = true
thiserror.workspace = true
serde.workspace = true
