[package]
name = "codegen-harness"
version = "0.1.0"
edition = "2021"

[dependencies]
rawr = { workspace = true }
schemas = { path = "../schemas" }
walkdir = { workspace = true }
colored = { workspace = true }
