[package]
name = "service-harness"
version = "0.1.0"
edition = "2021"

[dependencies]
rawr = { workspace = true }
schemas = { path = "../../test-codegen/schemas" }

anyhow = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
