[package]
name = "service-harness"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
duct = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
