[package]
name = "rawr_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.96" }
quote = { version = "1.0.38" }
proc-macro2 = { version = "1.0.93" }
